// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// API "feedpushr": output Resource Client
//
// Command:
// $ goagen
// --design=github.com/ncarlier/feedpushr/design
// --out=$(GOPATH)/src/github.com/ncarlier/feedpushr/autogen
// --version=v1.4.0

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListOutputPath computes a request path to the list action of output.
func ListOutputPath() string {

	return fmt.Sprintf("/v1/outputs")
}

// Retrieve all outputs definitions
func (c *Client) ListOutput(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListOutputRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListOutputRequest create the request corresponding to the list action endpoint of the output resource.
func (c *Client) NewListOutputRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
