// Code generated by goagen v1.4.3, DO NOT EDIT.
//
// API "feedpushr": vars Resource Client
//
// Command:
// $ goagen
// --design=github.com/ncarlier/feedpushr/v2/design
// --out=/home/nicolas/workspace/feedpushr/autogen
// --version=v1.4.3

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetVarsPath computes a request path to the get action of vars.
func GetVarsPath() string {

	return fmt.Sprintf("/v2/vars")
}

// Get all internals exp vars
func (c *Client) GetVars(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetVarsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetVarsRequest create the request corresponding to the get action endpoint of the vars resource.
func (c *Client) NewGetVarsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequestWithContext(ctx, "GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
