---
version: "3.7"
services:

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: feedpushr-selenium
    ports:
    - 4444:4444
    volumes:
    - /dev/shm:/dev/shm
    restart: unless-stopped
