// Code generated by goagen v1.4.3, DO NOT EDIT.
//
// API "feedpushr": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/ncarlier/feedpushr/v3/design
// --out=/home/nicolas/workspace/feedpushr/autogen
// --version=v1.4.3

package app
